#!/bin/bash

if [ ! -d ~/.bash-git-prompt ]
then
	git clone https://github.com/magicmonty/bash-git-prompt.git ~/.bash-git-prompt --depth=1

	echo `
GIT_PROMPT_ONLY_IN_REPO=1
GIT_PROMPT_THEME=Custom
GIT_PROMPT_PREFIX="("
GIT_PROMPT_SUFFIX=")"
GIT_PROMPT_START="\[\e[1;33m\][\u@\h \W\[\e[m\]"
GIT_PROMPT_END="\[\e[1;33m\]]$\[\e[m\] "
source ~/.bash-git-prompt/gitprompt.sh
` >> ~/.bashrc
fi
